<h1>Импорт библиотек

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

<h1>Задача 1. Дан набор из $p$ матриц размерностью $(n, n)$ и $p$ векторов размерностью $(n, 1)$, найти сумму произведений матриц на векторы. Написать тесты для кода

In [1]:
def sum_prod(X, V):
    '''
    X - список матриц размерности (n, n)
    V - список векторов размерности (n, 1)
    Гарантируется, что len(X) == len(V)
    '''
    result = np.zeros_like(V[0])
    for i in range(len(X)):
        result += np.dot(X[i], V[i])
        
    return result

# Тесты
def test_sum_prod():
    X1 = np.array([[1, 2], [3, 4]])  # Матрица 1
    X2 = np.array([[5, 6], [7, 8]])  # Матрица 2
    V1 = np.array([[1], [1]])        # Вектор 1
    V2 = np.array([[1], [1]])        # Вектор 2
    
    X = [X1, X2]
    V = [V1, V2]
    expected_result = np.dot(X1, V1) + np.dot(X2, V2)
    assert np.array_equal(sum_prod(X, V), expected_result), "Тест 1 не пройден"
    print("Тест 1 пройден")

test_sum_prod()

<h1>Задача 2. Дана матрица M, напишите функцию, которая бинаризует матрицу по некоторому threshold (то есть, все значения большие threshold становятся равными 1, иначе 0). Напишите тесты для кода

In [ ]:
import numpy as np

def binarize(M, threshold=0.5):
    '''
    M - входная матрица (numpy array)
    threshold - пороговое значение для бинаризации (по умолчанию 0.5)
    '''
    # Бинаризация матрицы: все значения больше threshold становятся 1, иначе 0
    return (M > threshold).astype(int)

# Тесты
def test_binarize():
    M1 = np.array([[0.2, 0.6], [0.8, 0.4]])
    threshold1 = 0.5
    expected1 = np.array([[0, 1], [1, 0]])
    assert np.array_equal(binarize(M1, threshold1), expected1), "Тест 1 не пройден"

    M2 = np.array([[0.1, 0.0], [-0.1, 0.5]])
    threshold2 = 0
    expected2 = np.array([[1, 0], [0, 1]])
    assert np.array_equal(binarize(M2, threshold2), expected2), "Тест 2 не пройден"

    M3 = np.array([[0.99, 1.0], [1.1, 0.4]])
    threshold3 = 1.0
    expected3 = np.array([[0, 0], [1, 0]])
    assert np.array_equal(binarize(M3, threshold3), expected3), "Тест 3 не пройден"

    print("Все тесты пройдены!")

test_binarize()


<h1>Задача 3. Напишите функцию, которая возвращает уникальные элементы из каждой строки матрицы. Напишите такую же функцию, но для столбцов. Напишите тесты для кода

In [ ]:
import numpy as np

def unique_rows(mat):
    '''
    Возвращает список массивов уникальных элементов для каждой строки матрицы
    '''
    return [np.unique(row) for row in mat]

def unique_columns(mat):
    '''
    Возвращает список массивов уникальных элементов для каждого столбца матрицы
    '''
    return [np.unique(mat[:, col]) for col in range(mat.shape[1])]

# Тесты
def test_unique_rows_columns():
    mat1 = np.array([[1, 2, 2], [3, 3, 1], [4, 4, 4]])
    
    expected_rows1 = [np.array([1, 2]), np.array([1, 3]), np.array([4])]
    assert all(np.array_equal(unique_rows(mat1)[i], expected_rows1[i]) for i in range(len(expected_rows1))), "Тест уникальных строк 1 не пройден"
    
    expected_cols1 = [np.array([1, 3, 4]), np.array([2, 3, 4]), np.array([1, 2, 4])]
    assert all(np.array_equal(unique_columns(mat1)[i], expected_cols1[i]) for i in range(len(expected_cols1))), "Тест уникальных столбцов 1 не пройден"
    
    mat2 = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
    
    expected_rows2 = [np.array([1]), np.array([1]), np.array([1])]
    expected_cols2 = [np.array([1]), np.array([1]), np.array([1])]
    
    assert all(np.array_equal(unique_rows(mat2)[i], expected_rows2[i]) for i in range(len(expected_rows2))), "Тест уникальных строк 2 не пройден"
    assert all(np.array_equal(unique_columns(mat2)[i], expected_cols2[i]) for i in range(len(expected_cols2))), "Тест уникальных столбцов 2 не пройден"
    
    print("Все тесты пройдены!")

test_unique_rows_columns()


<h1>Задача 4. Напишите функцию, которая заполняет матрицу с размерами $(m, n)$ случайными числами, распределенными по нормальному закону. Затем считает мат. ожидание и дисперсию для каждого из столбцов и строк, а также строит для каждой строки и столбца гистограмму значений (использовать функцию hist из модуля matplotlib.plot)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

def matrix_stats_and_histograms(rows, cols, mean=0, std_dev=1):
    mat = np.random.normal(mean, std_dev, size=(rows, cols))

    row_means = np.mean(mat, axis=1)
    row_vars = np.var(mat, axis=1)
    
    col_means = np.mean(mat, axis=0)
    col_vars = np.var(mat, axis=0)
    
    print("Мат. ожидание для каждой строки:", row_means)
    print("Дисперсия для каждой строки:", row_vars)
    print("Мат. ожидание для каждого столбца:", col_means)
    print("Дисперсия для каждого столбца:", col_vars)
    
    for i in range(rows):
        plt.figure()
        plt.hist(mat[i, :], bins=10, alpha=0.7, color='blue')
        plt.title(f'Гистограмма для строки {i+1}')
        plt.xlabel('Значения')
        plt.ylabel('Частота')
        plt.grid(True)
        plt.show()
    
    for j in range(cols):
        plt.figure()
        plt.hist(mat[:, j], bins=10, alpha=0.7, color='green')
        plt.title(f'Гистограмма для столбца {j+1}')
        plt.xlabel('Значения')
        plt.ylabel('Частота')
        plt.grid(True)
        plt.show()

matrix_stats_and_histograms(3, 4)


<h1>Задача 5. Напишите функцию, которая заполняет матрицу $(m, n)$ в шахматном порядке заданными числами $a$ и $b$. Напишите тесты для кода

In [ ]:
import numpy as np

def chess(m, n, a, b):

    mat = np.zeros((m, n))
    
    for i in range(m):
        for j in range(n):
            if (i + j) % 2 == 0:  
                mat[i, j] = a
            else:  
                mat[i, j] = b
    
    return mat

def test_chess():
    m1, n1 = 3, 3
    a1, b1 = 1, 0
    expected1 = np.array([[1, 0, 1], 
                          [0, 1, 0], 
                          [1, 0, 1]])
    assert np.array_equal(chess(m1, n1, a1, b1), expected1), "Тест 1 не пройден"

    m2, n2 = 4, 4
    a2, b2 = 2, 5
    expected2 = np.array([[2, 5, 2, 5], 
                          [5, 2, 5, 2], 
                          [2, 5, 2, 5], 
                          [5, 2, 5, 2]])
    assert np.array_equal(chess(m2, n2, a2, b2), expected2), "Тест 2 не пройден"
    
    m3, n3 = 2, 3
    a3, b3 = 9, -3
    expected3 = np.array([[9, -3, 9], 
                          [-3, 9, -3]])
    assert np.array_equal(chess(m3, n3, a3, b3), expected3), "Тест 3 не пройден"
    
    print("Все тесты пройдены!")

test_chess()


<h1>Задача 6. Напишите функцию, которая отрисовывает прямоугольник с заданными размерами (a, b) на изображении размера (m, n), цвет фона задайте в схеме RGB, как и цвет прямоугольника. Цвета также должны быть параметрами функции. Напишите аналогичную функцию но для овала с полуосями a и b. Напишите тесты для кода.
Примечание: уравнение эллипса (границы овала) можно записать как:
<h1>$\frac{(x-x_0)^2}{a^2}+\frac{(y-y_0)^2}{b^2}=1$

In [1]:
from PIL import Image, ImageDraw

def draw_rectangle(m, n, a, b, bg_color, rect_color):

    img = Image.new('RGB', (m, n), bg_color)
    draw = ImageDraw.Draw(img)
    
    left = (m - a) // 2
    top = (n - b) // 2
    right = left + a
    bottom = top + b
    
    draw.rectangle([left, top, right, bottom], fill=rect_color)
    return img

def draw_ellipse(m, n, a, b, bg_color, ellipse_color):

    img = Image.new('RGB', (m, n), bg_color)
    draw = ImageDraw.Draw(img)
    
    left = (m - a) // 2
    top = (n - b) // 2
    right = left + a
    bottom = top + b
    
    draw.ellipse([left, top, right, bottom], fill=ellipse_color)

    return img

# Тесты
def test_draw_shapes():
    img_rect = draw_rectangle(200, 200, 100, 50, (255, 255, 255), (255, 0, 0))
    img_rect.show()  
    

    img_ellipse = draw_ellipse(200, 200, 120, 60, (255, 255, 255), (0, 255, 0))
    img_ellipse.show() 

test_draw_shapes()


<h1>Задача 7. Дан некий временной ряд. Для данного ряда нужно найти его: математическое ожидание, дисперсию, СКО, найти все локальные максимумы и минимумы (локальный максимум - это точка, которая больше своих соседних точек, а локальный минимум - это точка, которая меньше своих соседей), а также вычислить для данного ряда другой ряд, получаемый методом скользящего среднего с размером окна $p$.
<h1>Примечание: метод скользящего среднего подразумевает нахождение среднего из подмножетсва ряда размером $p$

In [ ]:
import numpy as np

def time_series_analysis(series, p):
    
    mean = np.mean(series)
    
    variance = np.var(series)
    
    std_dev = np.std(series)
    
    local_maxima = []
    local_minima = []
    
    for i in range(1, len(series) - 1):
        if series[i] > series[i - 1] and series[i] > series[i + 1]:
            local_maxima.append((i, series[i]))  # добавляем индекс и значение
        elif series[i] < series[i - 1] and series[i] < series[i + 1]:
            local_minima.append((i, series[i]))  # добавляем индекс и значение
    
    moving_average = []
    for i in range(len(series) - p + 1):
        window = series[i:i + p]
        window_avg = np.mean(window)
        moving_average.append(window_avg)
    
    return {
        'mean': mean,
        'variance': variance,
        'std_dev': std_dev,
        'local_maxima': local_maxima,
        'local_minima': local_minima,
        'moving_average': moving_average
    }

def test_time_series_analysis():
    series = [1, 3, 7, 1, 2, 6, 0, 1, 4, 3, 2]
    p = 3
    
    result = time_series_analysis(series, p)
    
    print("Математическое ожидание:", result['mean'])
    print("Дисперсия:", result['variance'])
    print("СКО:", result['std_dev'])
    print("Локальные максимумы (индексы и значения):", result['local_maxima'])
    print("Локальные минимумы (индексы и значения):", result['local_minima'])
    print("Скользящее среднее с окном", p, ":", result['moving_average'])

test_time_series_analysis()


<h1> Задача 8. Дан некоторый вектор с целочисленными метками классов, напишите функцию, которая выполняет one-hot-encoding для данного вектора
<h1> One-hot-encoding - представление, в котором на месте метки некоторого класса стоит 1, в остальных позициях стоит 0. Например для вектора [0, 2, 3, 0] one-hot-encoding выглядит как: [[1, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 0, 0]]

In [ ]:
import numpy as np

def one_hot_encode(labels):
    labels = np.array(labels)
    num_classes = np.max(labels) + 1  
    one_hot = np.zeros((labels.size, num_classes))
    one_hot[np.arange(labels.size), labels] = 1
    
    return one_hot

labels = [0, 2, 3, 0]
one_hot = one_hot_encode(labels)
print(one_hot)

#Вывод
# [[1. 0. 0. 0.]
#  [0. 0. 1. 0.]
#  [0. 0. 0. 1.]
#  [1. 0. 0. 0.]]

def test_one_hot_encode():
    labels = [0, 1, 2, 3]
    expected = np.array([[1, 0, 0, 0],
                         [0, 1, 0, 0],
                         [0, 0, 1, 0],
                         [0, 0, 0, 1]])
    result = one_hot_encode(labels)
    assert np.array_equal(result, expected), f"Ожидалось {expected}, получено {result}"
    
    labels = [3, 2, 1, 0]
    expected = np.array([[0, 0, 0, 1],
                         [0, 0, 1, 0],
                         [0, 1, 0, 0],
                         [1, 0, 0, 0]])
    result = one_hot_encode(labels)
    assert np.array_equal(result, expected), f"Ожидалось {expected}, получено {result}"
    
    labels = [0, 0, 0, 0]
    expected = np.array([[1, 0, 0, 0],
                         [1, 0, 0, 0],
                         [1, 0, 0, 0],
                         [1, 0, 0, 0]])
    result = one_hot_encode(labels)
    assert np.array_equal(result, expected), f"Ожидалось {expected}, получено {result}"
    
    print("Все тесты пройдены.")

test_one_hot_encode()
